name: Update WSL-DistroLauncher Fork

on:
  schedule:
    - cron: "0 * * * *"   # jede Stunde
  workflow_dispatch:

jobs:
  update-fork:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/microsoft/WSL-DistroLauncher.git || true
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout master
          git merge upstream/master --allow-unrelated-histories --no-edit || echo "Nothing to merge"

      - name: Push changes to fork
        run: |
          git push origin master
